# Generated by Django 5.2.6 on 2025-09-19 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
